# Generated by Django 3.1 on 2020-08-08 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='batch',
            old_name='providers',
            new_name='provider',
        ),
    ]
